spring.application.name=twitterapi

server.port = 3000

spring.datasource.url=jdbc:postgresql://localhost:5432/twitter_api
spring.datasource.username=postgres
spring.datasource.password=Eheehe.111


//Yaz?lan kodlar?n otomatik güncellemesi//
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true